apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-node-conf
data:
  redis.conf: |
    maxmemory 980mb
    cluster-enabled yes
    cluster-config-file /tmp/nodes.conf
    cluster-node-timeout 5000
    appendonly yes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-node
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: redis-node
    spec:
      initContainers:
      - name: sysctl-somaxconn
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "net.core.somaxconn=65535"]
        securityContext:
          privileged: true
      volumes:
      - name: config-volume
        configMap:
          name: redis-node-conf
      containers:
      - name: redis-node
        image: redis:4.0.9
        imagePullPolicy: Always
        ports:
        - name: redis
          containerPort: 6379
        resources:
          limits:
            memory: 1024Mi
        args: ["/etc/redis/redis.conf"]
        volumeMounts:
        - name: config-volume 
          mountPath: /etc/redis/
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis-node
  ports:
    - name: redis
      protocol: TCP
      port: 6379
